import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  globalIgnores([
    ".next/**",
    "out/**",
    "build/**",
    "next-env.d.ts",
    // Vendored shadcn primitives: regenerated by the CLI, not hand-maintained.
    "src/components/ui/**",
  ]),
  {
    rules: {
      // A leading _ marks a deliberate discard.
      "@typescript-eslint/no-unused-vars": [
        "error",
        { argsIgnorePattern: "^_", varsIgnorePattern: "^_", caughtErrors: "none" },
      ],
      // Architecture rules, enforced rather than just documented.
      "no-restricted-imports": [
        "error",
        {
          patterns: [
            {
              group: ["../../*"],
              message: "Use the @/ alias instead of deep relative paths.",
            },
            {
              group: ["@/features/*/services/*", "@/features/*/hooks/*"],
              message: "Import a feature through its barrel: @/features/<feature>.",
            },
            {
              group: ["@/app/api/_lib/*"],
              message: "Server-only module. Import it from a Route Handler, never from a component.",
            },
          ],
        },
      ],
    },
  },
  {
    // Route Handlers import the server helpers; feature internals import their siblings.
    files: ["src/app/api/**/*.ts", "src/features/**/*.{ts,tsx}"],
    rules: { "no-restricted-imports": "off" },
  },
]);

export default eslintConfig;
